/**
 * 用户可见文案字典（v0.2.0 i18n，最小实现）。
 * 语言选择：浏览器语言以 zh 开头用中文，其余用英文（缺省中文）。
 * 音色名/镜像源等数据标签不翻译（保持原样），仅 UI 文案入字典。
 */

const zh = {
  stateVoiceMode: '语音模式',
  ttsNoticeFail: '朗读连接失败：正在重试…',
  enterFail: '进入语音模式失败',
  disabled: '语音模式已禁用（插件 enabled=false）',
  sendFailKept: '发送失败，已保留在草稿',
  micDenied: '麦克风被拒绝：请在浏览器地址栏允许麦克风权限',
  micUnavailable: '麦克风不可用',
  hold: '按住',
  recognizing: '识别中…',
  holdToTalk: '按住说话',
  voiceDetected: '语音中',
  entering: '进入中…',
  voiceBtn: '语音',
  ariaActive: '语音模式进行中',
  ariaEnter: '进入语音对话模式',
  titleHold: '语音模式进行中 · 按住说话、松手发送；短按退出；Esc/失去焦点放弃；Ctrl+Shift+V 退出',
  titleToggle: '语音模式进行中 · 点击退出（Ctrl+Shift+V）· 按住 Ctrl 立即发送',
  titleEnter: '进入语音对话模式（Ctrl+Shift+V）',
  loadingModel: '正在加载模型…',
  listening: '聆听中…',
  thinking: '思考中…',
  wakeWord: '唤醒词',
  barHold: '语音模式 · 按住说话（短按退出）',
  barListening: '语音模式 · 聆听中…',
  reading: '朗读中…',
  recognitionFail: '识别失败，请重试',
  sessionExpired: '语音会话已断开，正在重连…',
  sessionExpiredFail: '语音会话重连失败，请重新开启语音模式',
  modelDownloadFail: '语音模型下载失败（{file}）：请检查网络后重新进入语音模式重试',
  startFail: '语音模式启动失败：{err}',
  holdDots: '按住说话…',
  sayWake: '说「{wake}」开始',
  exit: '退出',
  skip: '跳过',
  configUnavailableNote: '（设置文档未就绪，面板就绪后会自动出现）。',
  // settings-form
  previewNameFirst: '请先填写音色名（ShortName）',
  previewDisabled: '语音模式已禁用（插件 enabled=false），无法试听',
  previewPlayFail: '试听失败：无法播放该音色',
  previewAutoplay: '浏览器拦截了自动播放，请再点一次试听',
  previewCheck: '试听失败：请检查网络或音色名（ShortName）是否正确',
  previewBtnTitle: '试听当前音色（当前语速）',
  synthesizing: '合成中…',
  preview: '试听',
  custom: '自定义',
  // settings rows
  descVoice: 'Edge TTS 音色（下拉常用，其余选「自定义」手动填 ShortName）',
  descRate: '朗读语速倍率（0.5 慢速 ～ 2.0 快速，1.0 正常）',
  descInterrupt: '发声打断灵敏度（0 高门槛 / 1 中 / 2 低；发声确认约 0.3/0.2/0.1 秒）',
  descBargeIn: '打断方式（auto 自动打断：开口即打断，耳机/安静环境推荐；manual 手动打断：外放推荐——回声不会误触发自打断，按住麦克风/Ctrl 显式打断）',
  bargeInAuto: '自动',
  bargeInManual: '手动',
  vadDetected: 'VAD 检测到语音',
  interruptConfirm: '打断确认',
  sev0: '0 高门槛',
  sev1: '1 中',
  sev2: '2 低',
  descSilence: '说完整一句的静音停顿毫秒数（默认 700 毫秒；至少 250ms 语音才判句，防短促噪声误触发）',
  descIdle: '无活动自动退出语音模式的分钟数（默认 10）',
  descModelHost: 'ASR 模型下载源（官方源 / 国内镜像，或选「自定义」填任意镜像）',
  descAutoSend: '识别定稿后自动发送（关=只进草稿；按住 Ctrl / hold 松手仍发送）',
  descSpokenFormat: '语音会话注入口语化提示词（回复口语化、不用 Markdown 排版符号，朗读更顺；默认关，改动即时生效）',
  descSenseVoice: '定稿用 SenseVoice 重译（带标点 + 数字归一化、识别更准；默认开。关闭可省 228MB 模型，只走流式识别）',
  descToolBeep: '工具执行提示音（默认关；开启后每个新工具响一次，防连续工具链叮叮叮）',
  descMode: '交互模式（toggle 持续聆听+静音断句 / hold 按住说话）',
  modeToggle: '持续聆听',
  modeHold: '按住说话',
  descWakeWord: '唤醒词（默认关；如「你好小D」，说出后开始识别）',
  wakePlaceholder: '如：你好小D',
  settingsCardDesc: '音色 / 语速 / 打断灵敏度 / 打断方式 / 静音停顿 / 空闲超时 / 模型镜像 / 自动发送 / 交互模式 / 唤醒词 / 口语化提示词',
  configUnavailable: '配置暂不可用',
  // telemetry（P1-5 开发模式延迟埋点状态条：各段耗时标签）
  telUtteranceEnd: '说完',
  telEndpoint: '端点',
  telSubmitted: '定稿',
  telFirstToken: '首Token',
  telFirstSentence: '首句',
  telFirstChunk: '首chunk',
  telFirstPlayed: '首音',
  // 模型管理（设置面板实时状态/重试）
  modelsTitle: '语音模型',
  modelsDisabled: '已关闭（设置中开启）',
  modelStreamingAsr: '流式识别',
  modelVad: '端点 VAD',
  modelSense: '定稿重译',
  modelsReady: '就绪',
  modelsDownloading: '{file} {percent}%',
  modelsFail: '下载失败（{sec} 秒后自动重试）',
  modelsMissing: '未下载',
  modelsRetry: '重试下载',
  modelsRetrying: '重试中…',
  modelsRetryHint: '镜像切换或下载失败后点击立即重试',
  modelsHint: '下载/进度实时跟进；失败自动退避 60s 重试。镜像源切换后点「重试下载」立即生效；也可用 npm run prefetch 预下载。',
  telTotal: '合计',
} as const

const en: Record<keyof typeof zh, string> = {
  stateVoiceMode: 'Voice Mode',
  ttsNoticeFail: 'Read-aloud connection lost: retrying…',
  enterFail: 'Failed to enter voice mode',
  disabled: 'Voice mode disabled (plugin enabled=false)',
  sendFailKept: 'Send failed; text kept in draft',
  micDenied: 'Microphone denied: allow mic access for this site',
  micUnavailable: 'Microphone unavailable',
  hold: 'Hold',
  recognizing: 'Recognizing…',
  holdToTalk: 'Hold to talk',
  voiceDetected: 'Voice active',
  entering: 'Entering…',
  voiceBtn: 'Voice',
  ariaActive: 'Voice mode active',
  ariaEnter: 'Enter voice mode',
  titleHold: 'Voice mode · hold to talk, release to send; tap to exit; Esc/blur cancels; Ctrl+Shift+V exits',
  titleToggle: 'Voice mode · click to exit (Ctrl+Shift+V) · hold Ctrl to send now',
  titleEnter: 'Enter voice mode (Ctrl+Shift+V)',
  loadingModel: 'Loading model…',
  listening: 'Listening…',
  thinking: 'Thinking…',
  wakeWord: 'Wake word',
  barHold: 'Voice mode · hold to talk (tap to exit)',
  barListening: 'Voice mode · listening…',
  reading: 'Reading…',
  recognitionFail: 'Recognition failed, try again',
  sessionExpired: 'Voice session expired, reconnecting…',
  sessionExpiredFail: 'Voice session reconnect failed; please re-enter voice mode',
  modelDownloadFail: 'Model download failed ({file}): check network and re-enter voice mode',
  startFail: 'Voice mode failed to start: {err}',
  holdDots: 'Hold to talk…',
  sayWake: 'Say "{wake}" to start',
  exit: 'Exit',
  skip: 'Skip',
  configUnavailableNote: ' (settings document not ready; the panel will appear when it is).',
  previewNameFirst: 'Enter a voice ShortName first',
  previewDisabled: 'Voice mode disabled; preview unavailable',
  previewPlayFail: 'Preview failed: cannot play this voice',
  previewAutoplay: 'Autoplay blocked — click preview again',
  previewCheck: 'Preview failed: check network or ShortName',
  previewBtnTitle: 'Preview voice (current rate)',
  synthesizing: 'Synthesizing…',
  preview: 'Preview',
  custom: 'Custom',
  descVoice: 'Edge TTS voice (presets, or a custom ShortName)',
  descRate: 'Speech rate (0.5 slow – 2.0 fast, 1.0 normal)',
  descInterrupt: 'Interrupt sensitivity (0 high barrier / 1 medium / 2 low; ~0.3/0.2/0.1 s speech confirmation)',
  descBargeIn: 'Barge-in mode (auto: interrupt by speaking — headphones/quiet; manual: for loudspeaker, no echo-triggered self-interrupt — hold mic/Ctrl to interrupt)',
  bargeInAuto: 'Auto',
  bargeInManual: 'Manual',
  vadDetected: 'VAD speech',
  interruptConfirm: 'interrupt confirm',
  sev0: '0 high',
  sev1: '1 medium',
  sev2: '2 low',
  descSilence: 'Silence pause before a sentence is committed (default 700 ms; at least 250 ms of speech required, guards against noise triggers)',
  descIdle: 'Auto-exit voice mode after idle minutes (default 10)',
  descModelHost: 'ASR model download source (official source / mirror, or any custom URL)',
  descAutoSend: 'Auto-send after finalized recognition (off = draft only; Ctrl / hold still sends)',
  descSpokenFormat: 'Inject spoken-format prompt into voice replies (colloquial, no Markdown; default off, live)',
  descSenseVoice: 'Re-transcribe the finalized utterance with SenseVoice (punctuation + ITN, more accurate; default on — turn off to skip the 228 MB model and keep streaming only)',
  descToolBeep: 'Tool-call beep (default off; when enabled, one short beep per new tool)',
  descMode: 'Interaction mode (toggle: continuous listen + auto-send / hold: press to talk)',
  modeToggle: 'Continue listen',
  modeHold: 'Hold to talk',
  descWakeWord: 'Wake word (default off; e.g. Hey D)',
  wakePlaceholder: 'e.g. Hey D',
  settingsCardDesc: 'Voice / rate / interrupt / barge-in / silence / idle / model host / auto-send / mode / wake word / spoken format',
  configUnavailable: 'Configuration unavailable',
  telUtteranceEnd: 'end',
  telEndpoint: 'endpoint',
  telSubmitted: 'submit',
  telFirstToken: '1st token',
  telFirstSentence: '1st sentence',
  telFirstChunk: '1st chunk',
  telFirstPlayed: '1st audio',
  modelsTitle: 'Voice models',
  modelsDisabled: 'off (enable in settings)',
  modelStreamingAsr: 'Streaming ASR',
  modelVad: 'Endpoint VAD',
  modelSense: 'Finalize',
  modelsReady: 'Ready',
  modelsDownloading: '{file} {percent}%',
  modelsFail: 'Download failed (auto-retry in {sec}s)',
  modelsMissing: 'not downloaded',
  modelsRetry: 'Retry',
  modelsRetrying: 'Retrying…',
  modelsRetryHint: 'Click to retry now after switching mirror or a failure',
  modelsHint: 'Live download state; failures auto-backoff 60s. After switching the mirror, click Retry to take effect immediately; npm run prefetch pre-downloads.',
  telTotal: 'total',
}

/**
 * 语言判定：**以 dsh 为准**——dsh 的语言设置（Settings → General → Language，
 * locale 命名空间，未设置时回退浏览器）解析后写入 <html lang>，页面加载时即已生效；
 * 插件不再自行探测浏览器语言。切换语言后按「刷新页面」生效（与 README 一致）。
 */
/** 每次调用时解析（组件渲染时 dsh 已写入最终 <html lang>），无缓存/无时序竞态。 */
const guess = (): 'zh' | 'en' =>
  /^zh\b/i.test(
    (typeof document !== 'undefined' && document.documentElement.lang) ||
      (typeof navigator !== 'undefined' ? navigator.language : '') ||
      '',
  )
    ? 'zh'
    : 'en'

/** 文案键类型（供组件侧声明含 t() 键的结构化配置）。 */
export type TKey = keyof typeof zh

export const t = (key: TKey): string => (guess() === 'zh' ? zh[key] : en[key] ?? zh[key])
