/**
 * 用户可见文案字典（v0.2.0 i18n，最小实现）。
 * 语言选择：浏览器语言以 zh 开头用中文，其余用英文（缺省中文）。
 * 音色名/镜像源等数据标签不翻译（保持原样），仅 UI 文案入字典。
 */

const zh = {
  stateVoiceMode: '语音模式',
  ttsNoticeFail: '朗读连接失败：正在重试…',
  enterFail: '进入语音模式失败',
  disabled: '语音模式已禁用（插件 enabled=false）',
  sendFailKept: '发送失败，已保留在草稿',
  micDenied: '麦克风被拒绝：请在浏览器地址栏允许麦克风权限',
  micUnavailable: '麦克风不可用',
  hold: '按住',
  recognizing: '识别中…',
  holdToTalk: '按住说话',
  voiceDetected: '语音中',
  entering: '进入中…',
  voiceBtn: '语音',
  ariaActive: '语音模式进行中',
  ariaEnter: '进入语音对话模式',
  titleHold: '语音模式进行中 · 按住说话、松手发送；短按退出；Esc/失去焦点放弃；Ctrl+Shift+V 退出',
  titleToggle: '语音模式进行中 · 点击退出（Ctrl+Shift+V）· 按住 Ctrl 立即发送',
  titleEnter: '进入语音对话模式（Ctrl+Shift+V）',
  loadingModel: '正在加载模型…',
  listening: '聆听中…',
  wakeWord: '唤醒词',
  barHold: '语音模式 · 按住说话（短按退出）',
  barListening: '语音模式 · 聆听中…',
  reading: '朗读中…',
  recognitionFail: '识别失败，请重试',
  modelDownloadFail: '语音模型下载失败（{file}）：请检查网络后重新进入语音模式重试',
  startFail: '语音模式启动失败：{err}',
  holdDots: '按住说话…',
  sayWake: '说「{wake}」开始',
  exit: '退出',
  skip: '跳过',
  configUnavailableNote: '（设置文档未就绪，面板就绪后会自动出现）。',
  // settings-form
  previewNameFirst: '请先填写音色名（ShortName）',
  previewDisabled: '语音模式已禁用（插件 enabled=false），无法试听',
  previewPlayFail: '试听失败：无法播放该音色',
  previewAutoplay: '浏览器拦截了自动播放，请再点一次试听',
  previewCheck: '试听失败：请检查网络或音色名（ShortName）是否正确',
  previewRateLimited: '试听太频繁了，稍候几秒再点（每分钟限 20 次）',
  previewTimeout: '合成超时：模型仍在加载，请稍候几秒再试',
  previewSynthesisFail: '合成失败',
  previewBtnTitle: '试听当前音色（当前语速）',
  synthesizing: '合成中…',
  preview: '试听',
  custom: '自定义',
  // settings rows
  voicePrev: '上一音色',
  voiceNext: '下一音色',
  modeBtnToggle: '持续聆听',
  modeBtnHold: '按住说',
  modeBtnTitle: '点击切换交互模式（保存到设置）',
  descVoice: 'Edge TTS 音色（◀▶ 左右切换常用音色，其余选「自定义」手动填 ShortName）',
  descVoiceLocal: '本地音色（vits-zh-ll 五说话人，◀▶ 切换；「自定义」可填 0-4 或英文名）',
  ttsEngine: '朗读引擎',
  descTtsEngine: '本地 VITS（纯中文）/ 本地 Kokoro（中英均可）/ Edge 云端（音质最自然，文本上微软）',
  engineVits: '本地 VITS',
  engineKokoro: '本地中英',
  engineEdge: 'Edge 云端',
  descVoiceKokoro: 'Kokoro 中英音色（103 个，◀▶ 左右切换；48-51 中文名，其余按编号+实测性别标注，中英混读均可）',
  descRate: '朗读语速倍率（0.5 慢速 ～ 2.0 快速，1.0 正常）',
  descInterrupt: '发声打断灵敏度（自适应：阈值随环境噪声自动浮动。0 高门槛 / 1 中 / 2 低；打断不了就往下调一档）',
  sev0: '0 高门槛',
  sev1: '1 中',
  sev2: '2 低',
  descSilence: '说完整一句的静音停顿毫秒数（默认 5000 = 5 秒）',
  descIdle: '无活动自动退出语音模式的分钟数（默认 10）',
  descModelHost: 'ASR 模型下载源（官方源 / 国内镜像，或选「自定义」填任意镜像）',
  descAutoSend: '识别定稿后自动发送（关=只进草稿；按住 Ctrl / hold 松手仍发送）',
  descSpokenFormat: '语音会话注入口语化提示词（回复口语化、不用 Markdown 排版符号，朗读更顺；默认关，改动即时生效）',
  descToolBeep: '工具调用提示音（默认关）：AI 思考/调用工具时"滴"一声；嫌吵就保持关闭',
  descMode: '交互模式（toggle 持续聆听+静音断句 / hold 按住说话）',
  modeToggle: '持续聆听',
  modeHold: '按住说话',
  descWakeWord: '唤醒词（默认关；如「你好小D」，说出后开始识别）',
  wakePlaceholder: '如：你好小D',
  settingsCardDesc: '朗读引擎 / 音色 / 语速 / 打断灵敏度 / 静音停顿 / 空闲超时 / 模型镜像 / 自动发送 / 交互模式 / 唤醒词 / 口语化提示词',
  configUnavailable: '配置暂不可用',
} as const

const en: Record<keyof typeof zh, string> = {
  stateVoiceMode: 'Voice Mode',
  ttsNoticeFail: 'Read-aloud connection lost: retrying…',
  enterFail: 'Failed to enter voice mode',
  disabled: 'Voice mode disabled (plugin enabled=false)',
  sendFailKept: 'Send failed; text kept in draft',
  micDenied: 'Microphone denied: allow mic access for this site',
  micUnavailable: 'Microphone unavailable',
  hold: 'Hold',
  recognizing: 'Recognizing…',
  holdToTalk: 'Hold to talk',
  voiceDetected: 'Voice active',
  entering: 'Entering…',
  voiceBtn: 'Voice',
  ariaActive: 'Voice mode active',
  ariaEnter: 'Enter voice mode',
  titleHold: 'Voice mode · hold to talk, release to send; tap to exit; Esc/blur cancels; Ctrl+Shift+V exits',
  titleToggle: 'Voice mode · click to exit (Ctrl+Shift+V) · hold Ctrl to send now',
  titleEnter: 'Enter voice mode (Ctrl+Shift+V)',
  loadingModel: 'Loading model…',
  listening: 'Listening…',
  wakeWord: 'Wake word',
  barHold: 'Voice mode · hold to talk (tap to exit)',
  barListening: 'Voice mode · listening…',
  reading: 'Reading…',
  recognitionFail: 'Recognition failed, try again',
  modelDownloadFail: 'Model download failed ({file}): check network and re-enter voice mode',
  startFail: 'Voice mode failed to start: {err}',
  holdDots: 'Hold to talk…',
  sayWake: 'Say "{wake}" to start',
  exit: 'Exit',
  skip: 'Skip',
  configUnavailableNote: ' (settings document not ready; the panel will appear when it is).',
  previewNameFirst: 'Enter a voice ShortName first',
  previewDisabled: 'Voice mode disabled; preview unavailable',
  previewPlayFail: 'Preview failed: cannot play this voice',
  previewAutoplay: 'Autoplay blocked — click preview again',
  previewCheck: 'Preview failed: check network or ShortName',
  previewRateLimited: 'Preview too frequent — wait a few seconds (20/min limit)',
  previewTimeout: 'Synthesis timed out: model still loading, retry in a few seconds',
  previewSynthesisFail: 'Synthesis failed',
  previewBtnTitle: 'Preview voice (current rate)',
  synthesizing: 'Synthesizing…',
  preview: 'Preview',
  custom: 'Custom',
  voicePrev: 'Previous voice',
  voiceNext: 'Next voice',
  modeBtnToggle: 'Continuous',
  modeBtnHold: 'Hold to talk',
  modeBtnTitle: 'Click to switch interaction mode (saved to settings)',
  descVoice: 'Edge TTS voice (◀▶ to cycle presets, or a custom ShortName)',
  descVoiceLocal: 'Local voice (vits-zh-ll, 5 speakers; ◀▶ to cycle; custom accepts 0-4 or a speaker name)',
  ttsEngine: 'Read-aloud engine',
  descTtsEngine: 'Local VITS (Chinese only) / Local Kokoro (Chinese + English) / Edge cloud (most natural, text sent to Microsoft)',
  engineVits: 'Local VITS',
  engineKokoro: 'Local zh-en',
  engineEdge: 'Edge cloud',
  descVoiceKokoro: 'Kokoro zh-en voices (103; ◀▶ to cycle; 48-51 named Chinese, others numbered with measured gender; mixed zh-en supported)',
  descRate: 'Speech rate (0.5 slow – 2.0 fast, 1.0 normal)',
  descInterrupt: 'Interrupt sensitivity (adaptive: threshold tracks the noise floor. 0 high barrier / 1 medium / 2 low; step down if barge-in misses)',
  sev0: '0 high',
  sev1: '1 medium',
  sev2: '2 low',
  descSilence: 'Silence pause before a sentence is committed (default 2000 ms)',
  descIdle: 'Auto-exit voice mode after idle minutes (default 10)',
  descModelHost: 'ASR model download source (official source / mirror, or any custom URL)',
  descAutoSend: 'Auto-send after finalized recognition (off = draft only; Ctrl / hold still sends)',
  descSpokenFormat: 'Inject spoken-format prompt into voice replies (colloquial, no Markdown; default off, live)',
  descToolBeep: 'Tool-call beep (default off): beep when the agent is thinking/calling tools; keep off if it annoys you',
  descMode: 'Interaction mode (toggle: continuous listen + auto-send / hold: press to talk)',
  modeToggle: 'Continue listen',
  modeHold: 'Hold to talk',
  descWakeWord: 'Wake word (default off; e.g. Hey D)',
  wakePlaceholder: 'e.g. Hey D',
  settingsCardDesc: 'Engine / voice / rate / interrupt / silence / idle / model host / auto-send / mode / wake word / spoken format',
  configUnavailable: 'Configuration unavailable',
}

/**
 * 语言判定：**以 dsh 为准**——dsh 的语言设置（Settings → General → Language，
 * locale 命名空间，未设置时回退浏览器）解析后写入 <html lang>，页面加载时即已生效；
 * 插件不再自行探测浏览器语言。切换语言后按「刷新页面」生效（与 README 一致）。
 */
/** 每次调用时解析（组件渲染时 dsh 已写入最终 <html lang>），无缓存/无时序竞态。 */
const guess = (): 'zh' | 'en' =>
  /^zh\b/i.test(
    (typeof document !== 'undefined' && document.documentElement.lang) ||
      (typeof navigator !== 'undefined' ? navigator.language : '') ||
      '',
  )
    ? 'zh'
    : 'en'

export const t = (key: keyof typeof zh): string => (guess() === 'zh' ? zh[key] : en[key] ?? zh[key])
