/**
 * 用户可见文案字典（zh / en 两份，键一一对应）。
 *
 * 语言选择与翻译函数在 i18n.ts：优先接入 dsh 官方客户端 locale 服务（`ctx.locale`，0.1.1 → 0.2.0 全版本有，
 * 切换语言即时生效、可被社区语言包扩展）；服务不可用时回退本文件末尾的本地实现（读 <html lang>）。
 * 音色名/镜像源等数据标签的「名称」不翻译，但其中的性别/口音等描述词走本字典（见 voice* / gender* / accent* 键）。
 */

export const zh = {
  stateVoiceMode: '语音模式',
  ttsNoticeFail: '朗读连接失败：正在重试…',
  ttsSkipNotice: '有一句朗读失败，已跳过（云端朗读网络抖动，可重发这条消息）',
  enterFail: '进入语音模式失败',
  disabled: '语音模式已禁用（插件 enabled=false）',
  sendFailKept: '发送失败，已保留在草稿',
  micDenied: '麦克风被拒绝：请在浏览器地址栏允许麦克风权限',
  micUnavailable: '麦克风不可用',
  recognizing: '识别中…',
  holdToTalk: '按住说话',
  releaseToSend: '松开发送',
  voiceDetected: '语音中',
  entering: '进入中…',
  voiceBtn: '语音',
  ariaActive: '语音模式进行中',
  ariaEnter: '进入语音对话模式',
  titleHold: '语音模式进行中 · 按住说话、松手发送；短按退出；Esc/失去焦点放弃；Ctrl+Shift+V 退出',
  titleToggle: '语音模式进行中 · 点击退出（Ctrl+Shift+V）· 按住 Ctrl 立即发送',
  titleEnter: '进入语音对话模式（Ctrl+Shift+V）',
  loadingModel: '正在加载模型…',
  listening: '聆听中…',
  thinking: '思考中…',
  barHold: '语音模式 · 按住说话（短按退出）',
  barListening: '语音模式 · 聆听中…',
  wakeWord: '唤醒词',
  sayWake: '说「{wake}」开始',
  reading: '朗读中…',
  recognitionFail: '识别失败，请重试',
  sessionExpired: '语音会话已断开，正在重连…',
  sessionExpiredFail: '语音会话重连失败，请重新开启语音模式',
  modelDownloadFail: '语音模型下载失败（{file}）：请检查网络后重新进入语音模式重试',
  startFail: '语音模式启动失败：{err}',
  holdDots: '按住说话…',
  exit: '退出',
  skip: '跳过',
  configUnavailableNote: '（设置文档未就绪，面板就绪后会自动出现）。',
  // settings-form
  previewNameFirst: '请先填写音色名（ShortName）',
  previewDisabled: '语音模式已禁用（插件 enabled=false），无法试听',
  // 批 G 任务 6：本地 TTS 引擎未下载模型时禁用试听按钮 + 提示。
  previewModelMissing: '请先下载本地模型（见上方「朗读引擎」状态）',
  previewModelLoading: '本地模型正在下载中，请稍候',
  previewPlayFail: '试听失败：无法播放该音色',
  previewAutoplay: '浏览器拦截了自动播放，请再点一次试听',
  previewCheck: '试听失败：请检查网络或音色名（ShortName）是否正确',
  previewRateLimited: '试听太频繁了，稍候几秒再点（每分钟限 20 次）',
  previewTimeout: '合成超时：模型仍在加载，请稍候几秒再试',
  previewBtnTitle: '试听当前音色（当前语速）',
  synthesizing: '合成中…',
  preview: '试听',
  custom: '自定义',
  // settings rows
  voicePrev: '上一音色',
  voiceNext: '下一音色',
  descVoice: 'Edge 云端音色（进入时自动加载微软全部音色，常用中文音色置顶，下拉或 ◀▶ 选；也可「自定义」填 ShortName）',
  descVoiceLocal: '本地音色（vits 五个说话人全部列出，下拉选或 ◀▶ 切换；无需自定义）',
  descTtsEngine: '本地 VITS（纯中文）/ 本地 Kokoro（中英均可）/ Edge 云端（音质最自然，文本上微软）',
  engineVits: '本地 VITS',
  engineKokoro: '本地中英',
  engineEdge: 'Edge 云端',
  descVoiceKokoro: 'Kokoro 中英音色（103 个全部列出，下拉选或 ◀▶ 切换；48-51 中文名，其余按编号+实测性别标注，中英混读均可）',
  descRate: '朗读语速倍率（0.5 慢速 ～ 2.0 快速，1.1 默认；让回复更紧凑）',
  descInterrupt: '发声打断灵敏度（0 高门槛 ≈0.3s 确认 / 1 中门槛 ≈0.2s / 2 低门槛 ≈0.1s，最灵敏）；值越低门槛越高，越难打断',
  descBargeIn: '打断方式（detect 自动探测本机回声消除状态、未生效时切为长按打断，默认；auto 强制自动打断：开口即打断，耳机/安静环境推荐；manual 手动打断：外放推荐——回声不会误触发自打断，按住麦克风/Ctrl 显式打断）',
  bargeInDetect: '自动探测',
  bargeInAuto: '自动',
  bargeInManual: '手动',
  descEchoGate: '回声门控阈值（dB，默认 6）：自动打断要求残差高于回声地板此值。当前 ASR 模型默认原生 AEC 生效时此门控闲置；Safari / 耳机等无原生 AEC 环境会兜底生效。外放仍误打断调大（8~10），太难打断调小（3~4）',
  descShortcut: '进入/退出语音模式的快捷键（形如 Ctrl+Shift+V；留空禁用快捷键，只用麦克风按钮；避免浏览器保留组合如 Ctrl+W/N/T）',
  vadDetected: 'VAD 检测到语音',
  aecOff: '原生回声消除未生效',
  aecOffHint: '浏览器原生回声消除未生效（外放可能自打断），建议用耳机或切换「手动打断」',
  // 批 7O（ADR-0006）：detect 模式第一级探测降级提示（状态条）。
  bargeInDetectFallback: '本机回声消除未生效，已切为长按打断',
  elapsedHint: '当前语音会话已用时长',
  botLevelsHint: 'AI 朗读音量（蓝色条 = 朗读，绿色条 = 麦克风）',
  interruptConfirm: '打断确认',
  sev0: '0 高门槛',
  sev1: '1 中',
  sev2: '2 低',
  descSilence: '说完整一句的静音停顿毫秒数（默认 1500 毫秒，给思考停顿留空间；至少 250ms 语音才判句，防短促噪声误触发）',
  descIdle: '无活动自动退出语音模式的分钟数（默认 5；批 G 任务 2 已加 30s 倒数预警）',
  descModelHost: 'ASR 模型下载源（官方源 / 国内镜像，或选「自定义」填任意镜像）',
  descAutoSend: '静音到点自动发送（连续多段拼成一条；关=只进草稿；按住 Ctrl / hold 松手仍发送）',
  // 批 7N 重做 5/5：明确「开启后下次进入语音会话即生效」——消除「点完为何不立即恢复」的预期差。
  descAutoResume: '切换回上次语音会话时自动恢复语音模式（默认关；开启后下次进入语音会话即生效——自动进入语音模式 + 恢复上次会话；关闭则需手动按 Ctrl+Shift+V 重新进入）',
  descSpokenFormat: '语音会话注入口语化提示词（回复口语化、短句、不用 Markdown 排版符号，朗读更顺更快；默认开，改动即时生效）',
  descSenseVoice: '定稿用 SenseVoice 重译（带标点 + 数字归一化、识别更准；默认开。关闭可省 228MB 模型，只走流式识别）',
  descToolBeep: '工具调用提示音（默认关）：AI 思考/调用工具时"滴"一声；嫌吵就保持关闭',
  senseITN: '逆文本归一化',
  descSenseITN: 'SenseVoice 数字/日期/格式规范化（默认开；关闭后输出更接近口语原文）',
  descCaptionFontSize: '浮层字幕字号档位（小 12 / 标准 14 / 大 18 / 特大 24 px；默认小与现状字节等价）',
  descCaptionMaxWidth: '浮层字幕宽度档位（50vw / 70vw / 90vw；默认 70vw；24px 多行时受 30vh 高度约束不盖输入框）',
  captionSizeS: '小',
  captionSizeM: '标准',
  captionSizeL: '大',
  captionSizeXL: '特大',
  captionWidth50: '窄',
  captionWidth70: '中',
  captionWidth90: '宽',
  skipReading: '跳过当前朗读',
  backchannelYield: '短应答让位',
  descBackchannelYield: '朗读期用户说「嗯/对」等短应答时自动让位（跳过当前 TTS 句 + 短暂丢帧 1.5s；真要说则原 hardBreak 接管；关 = 不让位，行为等同改造前）',
  // 批 G 任务 3：让位窗口时长（500-3000ms，默认 1500）。
  yieldMs: '让位窗口',
  descYieldMs: '让位语义触发后等待时长（毫秒，500-3000，默认 1500；窗口内用户真要说则原 hardBreak 接管，窗口到点自动恢复播放）',
  descMode: '交互模式（toggle 持续聆听+静音断句 / hold 按住说话）',
  modeToggle: '持续聆听',
  modeHold: '按住说话',
  descWakeWord: '唤醒词（默认关；如「你好小D」）：说出词头才进入识别，避免误触。可与命令连说（「你好小D，帮我查天气」——词头会自动剥掉、不进消息）；每句断句或打断后需重说；仅 toggle 模式生效（hold / 手动打断下不生效）；朗读期说唤醒词不触发（打断仍按 VAD 开口即打断）。匹配带容错（同音字 / 前导语气词），建议 3-4 字；非专用 KWS 引擎，嘈杂环境可能延迟或误激活',
  wakePlaceholder: '如：你好小D',
  settingsCardDesc: '朗读引擎 / 音色 / 语速 / 打断灵敏度 / 打断方式 / 回声门控 / 静音停顿 / 空闲超时 / 模型镜像 / 自动发送 / 自动恢复 / 交互模式 / 唤醒词 / 工具提示音 / 逆文本归一化 / 字幕字号 / 字幕宽度 / 短应答让位 / 让位窗口',
  settingsEffectiveNote: '朗读引擎 / 音色 / 语速 / 模型精度 / 口语化提示词 / 重译 / 字幕字号 / 字幕宽度 / 短应答让位 / 让位窗口 即时生效；逆文本归一化 即时生效（下次进入语音模式重建流式识别器）；其余（打断灵敏度 / 打断方式 / 回声门控 / 快捷键 / 静音 / 空闲 / 镜像 / 自动发送 / 自动恢复 / 交互模式 / 唤醒词 / 工具提示音）下次进入语音模式时生效。',
  configUnavailable: '配置暂不可用',
  // telemetry（P1-5 开发模式延迟埋点状态条：各段耗时标签）
  telUtteranceEnd: '说完',
  telEndpoint: '端点',
  telSubmitted: '定稿',
  telFirstToken: '首Token',
  telFirstSentence: '首句',
  telFirstChunk: '首chunk',
  telFirstPlayed: '首音',
  // 模型管理（设置面板实时状态/重试）
  modelsTitle: '语音模型',
  modelsDisabled: '已关闭（设置中开启）',
  modelStreamingAsr: '流式识别',
  modelVad: '端点 VAD',
  modelSense: '定稿重译',
  modelsReady: '就绪',
  modelsDownloading: '{file} {percent}%',
  modelsFail: '下载失败（{sec} 秒后自动重试）',
  modelsMissing: '未下载',
  modelsRetry: '重试下载',
  modelsRetrying: '重试中…',
  modelsRetryHint: '镜像切换或下载失败后点击立即重试',
  modelsHint: '下载/进度实时跟进；失败自动退避 60s 重试。镜像源切换后点「重试下载」立即生效；也可用 npm run prefetch 预下载。',
  // 朗读引擎状态（设置面板内联展示）
  engineLoading: '加载中…',
  engineReady: '就绪',
  engineError: '加载失败',
  errKokoroNeedsNode: '本地 Kokoro 无法在官方桌面端（Electron）内直接运行：请在系统 PATH 上安装 Node.js ≥18（或设环境变量 DSHVM_NODE 指向它），或把朗读引擎切换为 Edge / 本地 VITS。',
  ttsModelsMissing: '本地模型未就绪',
  ttsDownload: '下载',
  ttsDelete: '删除',
  ttsDownloading: '下载中…',
  ttsDeleting: '删除中…',
  ttsDownloadHint: '下载该引擎的本地模型；下载完成后立即就绪，可试听/朗读',
  ttsDeleteHint: '删除本地模型（释放空间；下次使用会自动重新下载）',
  dataFlowHint: '数据流向：ASR 识别（zipformer2+SenseVoice）始终本地；TTS 朗读取决于引擎（edge=微软云端，vits/kokoro=本地）',
  kokoroModel: 'Kokoro 模型精度',
  kokoroModelInt8: 'int8（默认）',
  kokoroModelFp32: 'fp32（音质更好）',
  descKokoroModel: 'Kokoro 模型精度：int8 体积小/加载快（纯 CPU 服务器或低带宽推荐，默认）；fp32 音质更好但约 311MB、更慢（有独立显卡或大内存机器推荐）。两档共用同一套 103 音色，切换即时生效。',
  // 设置分组标题
  secRead: '朗读与音色',
  secInterrupt: '打断与静音',
  secInteraction: '交互与输入',
  secRecognition: '识别与口语',
  secModel: '模型与镜像',
  telTotal: '合计',
  // 批 C：FIELD_LABELS 镜像键（*Label 后缀；详见 settings-form.tsx 头部注释）。
  // 临时双轨——与 FIELD_LABELS 并行维护同一组中文，未来整合批去掉 FIELD_LABELS，
  // 统一改用 tr() 翻译键模式避免双轨漂移风险。en 段对应 stub 见下方 en 对象。
  senseITNLabel: '逆文本归一化',
  captionFontSizeLabel: '字幕字号',
  captionMaxWidthLabel: '字幕宽度',
  backchannelYieldLabel: '短应答让位',
  // 批 G 任务 3：让位窗口（FIELD_LABELS.yieldMs 镜像键，*Label 后缀）。
  yieldMsLabel: '让位窗口',
  // 批 G 任务 2：空闲预警 + 退出提示文案。
  idleWarn30s: '30 秒后自动退出（设置里可调空闲时长）',
  idleTimeoutQuit: '空闲超时已自动退出（设置里可调时长）',
  // 批 G 任务 1：Number 校验红框 + clamp 提示。
  numberInvalid: '数值非法',
  numberClamped: '已自动调整为 {value}',
  // 批 H 任务 4：autoResume 关 + 切回上次语音会话时的引导提示（5s 后自动清）。
  // 批 7N 重做 2/5：明确「自动恢复」=「自动进入语音模式 + 恢复上次会话」。
  autoResumeHint: '「自动恢复」= 开启后切换回上次语音会话会自动进入语音模式并恢复上次会话；关闭则需手动按 Ctrl+Shift+V',
  // —— 国际化补全（字段标题/音色描述词/错误码文案/试听分类）——
  ttsEngineLabel: '朗读引擎',
  kokoroModelLabel: 'Kokoro 模型精度',
  voiceLabel: '音色',
  rateLabel: '语速',
  interruptLevelLabel: '打断灵敏度',
  bargeInModeLabel: '打断方式',
  echoGateDbLabel: '回声门控',
  modeLabel: '交互模式',
  shortcutLabel: '快捷键',
  wakeWordLabel: '唤醒词',
  toolBeepLabel: '工具提示音',
  autoSendLabel: '自动发送',
  autoResumeLabel: '自动恢复',
  senseVoiceLabel: '定稿重译',
  spokenFormatLabel: '口语化提示词',
  silenceMsLabel: '静音停顿',
  idleTimeoutMinutesLabel: '空闲超时',
  modelHostLabel: '模型镜像',
  genderFemale: '女',
  genderMale: '男',
  genderNeutral: '中性',
  accentMandarin: '简体中文',
  accentNortheast: '东北话',
  accentShaanxi: '陕西话',
  accentCantonese: '粤语',
  accentTaiwan: '台湾腔',
  accentEnglish: 'English',
  styleDeep: '深沉',
  styleRich: '浑厚',
  styleClear: '清亮',
  styleMagnetic: '磁性',
  voiceKokoroPopularMale: '常用男声',
  voiceKokoroChineseFemale: '中文女',
  voiceKokoroMale: '男声',
  voiceKokoroFemale: '女声',
  voiceKokoroGeneric: '音色',
  hostOfficial: '官方源',
  hostMirror: '国内镜像',
  engineBadgeCloud: '识别本地 · 朗读云端',
  engineBadgeLocal: '识别本地 · 朗读本地',
  errRateLimited: '请求过于频繁，请稍后再试',
  errUnknownSession: '语音会话已失效，请重新开启语音模式',
  errForbidden: '请求被拒绝（仅限本机访问，或来源不符）',
  errBadRequest: '请求无效',
  errEngineNotActive: '该朗读引擎当前未启用',
  errModelDownload: '模型下载失败：请检查网络',
  errTooManyStreams: '语音连接过多，请关闭其它语音页面后重试',
  errTooLarge: '请求内容过大',
  errInternal: '服务出错，请稍后重试',
  previewNetwork: '试听失败：网络不可达（Edge 云端需访问微软语音服务），请检查网络或代理',
  previewEngine: '试听失败：引擎未就绪（本地模型下载中、初始化失败或子进程异常），请稍后再试或在设置面板查看 TTS 状态',
  previewText: '试听失败：合成引擎产出空音频（音色与语种可能不匹配），请更换音色或检查语言设置',
  voiceHintChineseVoice: '提示：当前是中文音色；若主要用英文对话，建议在列表中选择英文音色（en-…）。',
  voiceHintEnglishVoice: '提示：当前是英文音色，朗读中文回复效果不佳；中文对话建议选择中文音色（zh-…）。',
} as const

export const en: Record<keyof typeof zh, string> = {
  stateVoiceMode: 'Voice Mode',
  ttsNoticeFail: 'Read-aloud connection failed: retrying…',
  ttsSkipNotice: 'One sentence failed to read and was skipped (cloud TTS network hiccup — resend the message to retry)',
  enterFail: 'Failed to enter voice mode',
  disabled: 'Voice mode disabled (plugin enabled=false)',
  sendFailKept: 'Send failed; text kept in draft',
  micDenied: 'Microphone denied: allow mic access for this site',
  micUnavailable: 'Microphone unavailable',
  recognizing: 'Recognizing…',
  holdToTalk: 'Hold to talk',
  releaseToSend: 'Release to send',
  voiceDetected: 'Voice active',
  entering: 'Entering…',
  voiceBtn: 'Voice',
  ariaActive: 'Voice mode active',
  ariaEnter: 'Enter voice mode',
  titleHold: 'Voice mode · hold to talk, release to send; tap to exit; Esc/blur cancels; Ctrl+Shift+V exits',
  titleToggle: 'Voice mode · click to exit (Ctrl+Shift+V) · hold Ctrl to send now',
  titleEnter: 'Enter voice mode (Ctrl+Shift+V)',
  loadingModel: 'Loading model…',
  listening: 'Listening…',
  thinking: 'Thinking…',
  barHold: 'Voice mode · hold to talk (tap to exit)',
  barListening: 'Voice mode · listening…',
  wakeWord: 'Wake word',
  sayWake: 'Say "{wake}" to start',
  reading: 'Reading aloud…',
  recognitionFail: 'Recognition failed, try again',
  sessionExpired: 'Voice session expired, reconnecting…',
  sessionExpiredFail: 'Voice session reconnect failed; please re-enter voice mode',
  modelDownloadFail: 'Model download failed ({file}): check network and re-enter voice mode',
  startFail: 'Voice mode failed to start: {err}',
  holdDots: 'Hold to talk…',
  exit: 'Exit',
  skip: 'Skip',
  configUnavailableNote: ' (settings document not ready; the panel will appear when it is).',
  previewNameFirst: 'Enter a voice ShortName first',
  previewDisabled: 'Voice mode disabled (plugin enabled=false); preview unavailable',
  // 批 G 任务 6：本地 TTS 引擎未下载模型时禁用试听按钮 + 提示。
  previewModelMissing: 'Download the local model first (see the engine status above)',
  previewModelLoading: 'Local model is downloading — please wait',
  previewPlayFail: 'Preview failed: cannot play this voice',
  previewAutoplay: 'Autoplay blocked — click preview again',
  previewCheck: 'Preview failed: check network or ShortName',
  previewRateLimited: 'Preview too frequent — wait a few seconds (20/min limit)',
  previewTimeout: 'Synthesis timed out: model still loading, retry in a few seconds',
  previewBtnTitle: 'Preview voice (current rate)',
  synthesizing: 'Synthesizing…',
  preview: 'Preview',
  custom: 'Custom',
  voicePrev: 'Previous voice',
  voiceNext: 'Next voice',
  descVoice: 'Edge cloud voices (auto-loads all Microsoft voices; common Chinese voices pinned on top; ◀▶ or dropdown; custom ShortName allowed)',
  descVoiceLocal: 'Local voice (vits, all 5 speakers listed; dropdown or ◀▶; no custom needed)',
  descTtsEngine: 'Local VITS (Chinese only) / Local Kokoro (Chinese + English) / Edge cloud (most natural, text sent to Microsoft)',
  engineVits: 'Local VITS',
  engineKokoro: 'Local Kokoro',
  engineEdge: 'Edge cloud',
  descVoiceKokoro: 'Kokoro zh-en voices (103; ◀▶ to cycle; 48-51 named Chinese, others numbered with measured gender; mixed zh-en supported)',
  descRate: 'Speech rate (0.5 slow – 2.0 fast, 1.1 default; more compact replies)',
  descInterrupt: 'Interrupt sensitivity (0 high ≈0.3 s confirm / 1 medium ≈0.2 s / 2 low ≈0.1 s, most responsive); lower = higher barrier = harder to interrupt',
  descBargeIn: 'Barge-in mode (detect: auto-probe native echo cancellation, fall back to hold-to-talk when inactive — default; auto: force interrupt by speaking — headphones/quiet; manual: for loudspeaker, no echo-triggered self-interrupt — hold mic/Ctrl to interrupt)',
  bargeInDetect: 'Auto-detect',
  bargeInAuto: 'Auto',
  bargeInManual: 'Manual',
  descEchoGate: 'Echo gate threshold (dB, default 6): auto barge-in requires the residual to exceed the echo floor by this value. With the native browser AEC active, this gate is idle; it kicks in as a fallback in Safari or environments without native AEC (e.g. some headphones). Raise (8-10) if speaker echo still interrupts, lower (3-4) if hard to interrupt',
  descShortcut: 'Shortcut to enter/exit voice mode (e.g. Ctrl+Shift+V; empty disables it, mic button only; avoid browser-reserved combos like Ctrl+W/N/T)',
  vadDetected: 'VAD speech',
  aecOff: 'Native AEC off',
  aecOffHint: 'Native echo cancellation is not active (speaker echo may self-interrupt); use headphones or Manual barge-in',
  // 批 7O（ADR-0006）：detect 模式第一级探测降级提示（英文）。
  bargeInDetectFallback: 'Native echo cancellation is off — switched to hold-to-talk barge-in',
  elapsedHint: 'Current voice session duration',
  botLevelsHint: 'AI playback level (blue bar = TTS playback, green bar = microphone)',
  interruptConfirm: 'interrupt confirm',
  sev0: '0 high',
  sev1: '1 medium',
  sev2: '2 low',
  descSilence: 'Silence pause before a sentence is committed (default 1500 ms; at least 250 ms of speech required, guards against noise triggers)',
  descIdle: 'Auto-exit voice mode after idle minutes (default 5; batch G added 30 s warning before exit)',
  descModelHost: 'ASR model download source (official source / mirror, or any custom URL)',
  descAutoSend: 'Auto-send once quiet (consecutive segments join into one message; off = draft only; Ctrl / hold still sends)',
  // 批 7N 重做 5/5：clarify that toggling takes effect on next session entry (not the current one).
  descAutoResume: 'Auto-resume voice mode when switching back to the last voice session (default off; takes effect on next session entry — auto-enters voice mode and restores the last session; when disabled, you must press Ctrl+Shift+V to re-enter)',
  descSpokenFormat: 'Inject spoken-format prompt into voice replies (colloquial, short sentences, no Markdown; default on, live)',
  descSenseVoice: 'Re-transcribe the finalized utterance with SenseVoice (punctuation + ITN, more accurate; default on — turn off to skip the 228 MB model and keep streaming only)',
  descToolBeep: 'Tool-call beep (default off): beep when the agent is thinking/calling tools; keep off if it annoys you',
  senseITN: 'Inverse text normalization',
  descSenseITN: 'SenseVoice number/date/format normalization (default on; turn off to keep raw spoken form)',
  descCaptionFontSize: 'Caption font size (Small 12 / Standard 14 / Large 18 / X-Large 24 px; default Small matches current behavior)',
  descCaptionMaxWidth: 'Caption width (50vw / 70vw / 90vw; default 70vw; capped at 30vh height so multi-line 24px never overlaps the input box)',
  captionSizeS: 'S',
  captionSizeM: 'M',
  captionSizeL: 'L',
  captionSizeXL: 'XL',
  captionWidth50: 'Narrow',
  captionWidth70: 'Medium',
  captionWidth90: 'Wide',
  skipReading: 'Skip current reading',
  backchannelYield: 'Short-reply yielding',
  descBackchannelYield: 'When the user says a short answer like "mm-hmm/right" while the agent is reading aloud, yield automatically (skip the current TTS sentence + drop frames for 1.5s; if the user really wants to speak, the existing hardBreak takes over; off = no yielding, behavior matches pre-batch-5)',
  // 批 G 任务 3：让位窗口时长（500-3000ms，默认 1500）。
  yieldMs: 'Yield window',
  descYieldMs: 'How long (ms) to drop frames after a yield trigger (500-3000, default 1500; within the window the existing hardBreak takes over if the user really wants to speak; auto-resume after the window expires)',
  descMode: 'Interaction mode (toggle: continuous listen + auto-send / hold: press to talk)',
  modeToggle: 'Continuous listening',
  modeHold: 'Hold to talk',
  descWakeWord: 'Wake word (default off; e.g. "Hey D"): recognition starts only after you say it, to avoid accidental triggers. You may say it together with your command ("Hey D, check the weather" — the wake word is stripped and never sent); it must be repeated after each utterance split or barge-in; toggle mode only (inactive in hold / manual barge-in); saying it while the agent is reading does not trigger (barge-in stays VAD-based). Fault-tolerant matching (homophones / leading fillers); 3-4 characters recommended; not a dedicated KWS engine — noisy environments may delay or falsely trigger',
  wakePlaceholder: 'e.g. Hey D',
  settingsCardDesc: 'Engine / voice / rate / interrupt / barge-in / echo gate / silence / idle / model host / auto-send / auto-resume / mode / wake word / tool beep / ITN / caption font / caption width / yielding / yield window',
  settingsEffectiveNote: 'Engine / voice / rate / model precision / spoken format / re-transcribe / caption font / caption width / yielding / yield window apply immediately; ITN applies immediately (next time you enter voice mode the streaming recognizer is rebuilt); the rest (interrupt / barge-in / echo gate / shortcut / silence / idle / mirror / auto-send / auto-resume / mode / wake word / tool beep) apply next time you enter voice mode.',
  configUnavailable: 'Configuration unavailable',
  telUtteranceEnd: 'end',
  telEndpoint: 'endpoint',
  telSubmitted: 'submit',
  telFirstToken: '1st token',
  telFirstSentence: '1st sentence',
  telFirstChunk: '1st chunk',
  telFirstPlayed: '1st audio',
  modelsTitle: 'Voice models',
  modelsDisabled: 'off (enable in settings)',
  modelStreamingAsr: 'Streaming ASR',
  modelVad: 'Endpoint VAD',
  modelSense: 'Finalize',
  modelsReady: 'Ready',
  modelsDownloading: '{file} {percent}%',
  modelsFail: 'Download failed (auto-retry in {sec}s)',
  modelsMissing: 'not downloaded',
  modelsRetry: 'Retry',
  modelsRetrying: 'Retrying…',
  modelsRetryHint: 'Click to retry now after switching mirror or a failure',
  modelsHint: 'Live download state; failures auto-backoff 60s. After switching the mirror, click Retry to take effect immediately; npm run prefetch pre-downloads.',
  engineLoading: 'loading…',
  engineReady: 'ready',
  engineError: 'failed',
  errKokoroNeedsNode: 'Local Kokoro cannot run directly inside the official desktop app (Electron): install Node.js >= 18 on PATH (or set DSHVM_NODE to its path), or switch the read-aloud engine to Edge / local VITS.',
  ttsModelsMissing: 'local models missing',
  ttsDownload: 'Download',
  ttsDelete: 'Delete',
  ttsDownloading: 'Downloading…',
  ttsDeleting: 'Deleting…',
  ttsDownloadHint: "Download this engine's local model; becomes ready immediately after",
  dataFlowHint: 'Data flow: ASR recognition (zipformer2+SenseVoice) is always local; TTS playback depends on engine (edge=Microsoft cloud, vits/kokoro=local)',
  ttsDeleteHint: 'Delete local models (frees space; auto re-downloads on next use)',
  kokoroModel: 'Kokoro model precision',
  kokoroModelInt8: 'int8 (default)',
  kokoroModelFp32: 'fp32 (better quality)',
  descKokoroModel: 'Kokoro model precision: int8 is smaller/faster (CPU server or low bandwidth; default); fp32 sounds better but ~311MB and slower (GPU or large memory). Both share the same 103 voices; switches live.',
  secRead: 'Reading & voice',
  secInterrupt: 'Interrupt & silence',
  secInteraction: 'Interaction',
  secRecognition: 'Recognition & speech',
  secModel: 'Model & mirror',
  telTotal: 'total',
  // 字段标题（Row 标题）：settings-form 经 tr(`${name}Label`) 取值，zh/en 均为正式文案。
  senseITNLabel: 'Inverse text normalization',
  captionFontSizeLabel: 'Caption size',
  captionMaxWidthLabel: 'Caption width',
  backchannelYieldLabel: 'Short-reply yielding',
  // 批 G 任务 3：让位窗口（FIELD_LABELS.yieldMs 镜像键，*Label 后缀）。
  yieldMsLabel: 'Yield window',
  // 批 G 任务 2：空闲预警 + 退出提示文案。
  idleWarn30s: 'Auto-exit in 30 seconds (adjustable in settings)',
  idleTimeoutQuit: 'Idle timeout — voice mode auto-exited (adjustable in settings)',
  // 批 G 任务 1：Number 校验红框 + clamp 提示。
  numberInvalid: 'Invalid number',
  numberClamped: 'Auto-clamped to {value}',
  // 批 H 任务 4：autoResume 关 + 切回上次语音会话时的引导提示（5s 后自动清）。
  // 批 7N 重做 2/5：明确「自动恢复」=「自动进入语音模式 + 恢复上次会话」。
  autoResumeHint: '"Auto-resume" = when enabled, switching back to your last voice session auto-enters voice mode and restores the session; when disabled, press Ctrl+Shift+V to re-enter',
  // —— i18n completion (field labels / voice descriptors / error-code copy / preview categories) ——
  ttsEngineLabel: 'Read-aloud engine',
  kokoroModelLabel: 'Kokoro model precision',
  voiceLabel: 'Voice',
  rateLabel: 'Speed',
  interruptLevelLabel: 'Interrupt sensitivity',
  bargeInModeLabel: 'Interrupt mode',
  echoGateDbLabel: 'Echo gate',
  modeLabel: 'Interaction mode',
  shortcutLabel: 'Shortcut',
  wakeWordLabel: 'Wake word',
  toolBeepLabel: 'Tool-call beep',
  autoSendLabel: 'Auto-send',
  autoResumeLabel: 'Auto-resume',
  senseVoiceLabel: 'Re-transcribe on finalize',
  spokenFormatLabel: 'Spoken-style prompt',
  silenceMsLabel: 'Silence pause',
  idleTimeoutMinutesLabel: 'Idle timeout',
  modelHostLabel: 'Model mirror',
  genderFemale: 'Female',
  genderMale: 'Male',
  genderNeutral: 'Neutral',
  accentMandarin: 'Mandarin',
  accentNortheast: 'Northeastern',
  accentShaanxi: 'Shaanxi',
  accentCantonese: 'Cantonese',
  accentTaiwan: 'Taiwanese Mandarin',
  accentEnglish: 'English',
  styleDeep: 'Deep',
  styleRich: 'Rich',
  styleClear: 'Clear',
  styleMagnetic: 'Magnetic',
  voiceKokoroPopularMale: 'Popular male',
  voiceKokoroChineseFemale: 'Chinese female',
  voiceKokoroMale: 'Male',
  voiceKokoroFemale: 'Female',
  voiceKokoroGeneric: 'Voice',
  hostOfficial: 'Official',
  hostMirror: 'Mirror (CN)',
  engineBadgeCloud: 'ASR local · TTS cloud',
  engineBadgeLocal: 'ASR local · TTS local',
  errRateLimited: 'Too many requests — try again shortly',
  errUnknownSession: 'Voice session expired — re-enter voice mode',
  errForbidden: 'Request denied (local access only, or origin mismatch)',
  errBadRequest: 'Invalid request',
  errEngineNotActive: 'That read-aloud engine is not active',
  errModelDownload: 'Model download failed — check your network',
  errTooManyStreams: 'Too many voice connections — close other voice tabs and retry',
  errTooLarge: 'Request too large',
  errInternal: 'Server error — please retry shortly',
  previewNetwork: 'Preview failed: network unreachable (Edge cloud needs the Microsoft speech service) — check your network or proxy',
  previewEngine: 'Preview failed: engine not ready (local model downloading, init failed, or worker crashed) — retry later or check TTS status in settings',
  previewText: 'Preview failed: the engine produced empty audio (voice and language may not match) — pick another voice',
  voiceHintChineseVoice: 'Note: this is a Chinese voice. For English replies, pick an English voice (en-…) from the list.',
  voiceHintEnglishVoice: 'Note: this is an English voice and reads Chinese replies poorly. For Chinese conversations, pick a Chinese voice (zh-…).',
}

/**
 * 本地回退语言判定（仅在官方 locale 服务不可用时使用）：<html lang> 以 zh 开头为中文，其余英文。
 * 每次调用时解析，无缓存。
 */
export const htmlLangIsZh = (): boolean =>
  /^zh\b/i.test(
    (typeof document !== 'undefined' && document.documentElement.lang) ||
      (typeof navigator !== 'undefined' ? navigator.language : '') ||
      '',
  )

/** 文案键类型（供组件侧声明含 t() 键的结构化配置）。 */
export type TKey = keyof typeof zh

/** 本地回退翻译：按语言取词，缺失回落英文（与官方 locale 服务的回退链一致：当前语言 → en）。 */
export const translateLocal = (key: TKey, isZh: boolean): string => (isZh ? zh[key] : en[key]) ?? en[key] ?? key
